name: Go
on: [push, pull_request]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Run influxdb image
        run: 'docker run -d --name influxdb -p 9999:9999 quay.io/influxdb/influxdb:2.0.0-beta'

      - name: Go fmt
        run: make fmt

      - name: Go test
        run: make test

      - name: Go testacc
        run: make testacc